#!/bin/bash

set -e

dir="$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )"

args=()

while [ "$1" != "" ]
do
    case $1 in
        -Wl,-Bdynamic)
            echo "remapping -Wl,-Bdynamic to -Wl,-search_paths_first"
            args+=("-Wl,-search_paths_first")
        ;;
        *list.def|-Wl,--disable-auto-image-base|-Wl,--dynamicbase|-Wl,--large-address-aware|-lwindows|-l:libpthread.a|-lgcc|-lwindows.0.52.0|-lgcc_eh|-lmsvcrt|*libcompiler_builtins*|-lgcc_s)
            echo "ignoring arg: $1"
            ;;
        * )
            args+=("$1")
            ;;
    esac
    shift
done

echo "new args:"
echo "${args[@]}"

"$dir/../../zig" cc -target x86_64-windows -lunwind "${args[@]}"