#!/bin/bash

set -e

dir="$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )"

while [ "$1" != "" ]; do
    case $1 in
        -i | --input )
            shift
            input_file="$1"
            ;;
        -o | --output )
            shift
            output_file="$1"
            ;;
        --include-dir)
            shift
            include_dir="$1"
            ;;
        * )
            other_args="$other_args $1"
            ;;
    esac
    shift
done

echo "ignored args: $other_args"
"$dir/../../zig" rc /i "$include_dir" /fo "$output_file" "$input_file"