#!/bin/bash

set -e

dir="$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )"

root_dir="$dir/.."
godot_dir="${GODOT_CROSS_GODOT_DIR:="$root_dir/gitignore/godot"}"

echo "$(cat <<EOF
export GODOT_CROSS_GODOT_DIR="$godot_dir"
export GODOT_CROSS_IMPORT_ENV_VARS="ZIG_GLOBAL_CACHE_DIR,ZIG_LOCAL_CACHE_DIR,GODOT_CROSS_CONFIG_DIR,GODOT_CROSS_GODOT_DIR,GODOT_CROSS_AUTO_INSTALL_GODOT,GODOT_CROSS_GODOT_NIR_DIR,GODOT_CROSS_AUTO_INSTALL_GODOT_NIR,GODOT_CROSS_GODOT_CUSTOM_MODULES"
EOF
)"
