#!/bin/bash

set -e

dir="$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )"

# Look!  I'm actually c++!  Idk who, but someone is incorrectly passing cpp files to cc.
# Fortunately zig c++ can also compile c so we are fine.  Thanks zig! :)
"$dir/../../zig" c++ -target x86_64-windows -lunwind "${args[@]}"