#!/bin/bash

set -e

dir="$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )"

args=()

dash_arg=""

# Remap clang args to the equivalent zig args
while [ "$1" != "" ]
do
    case $1 in
        --target=x86_64-pc-windows-gnu )
            echo "remapping '--target=x86_64-pc-windows-gnu' to '--target=x86_64-windows-gnu'"
            args+=("--target=x86_64-windows-gnu")
            zig_target_arg="-target x86_64-windows-gnu"
            ;;
        --target=x86_64-pc-windows-msvc )
            echo "remapping '--target=x86_64-pc-windows-msvc' to '--target=x86_64-windows-msvc'"
            args+=("--target=x86_64-windows-msvc")
            zig_target_arg="-target x86_64-windows"
            ;;
        --target=x86_64-pc-linux-gnu )
            echo "remapping '--target=x86_64-pc-linux-gnu' to '--target=x86_64-linux-gnu'"
            args+=("--target=x86_64-linux-gnu")
            zig_target_arg="-target x86_64-linux-gnu"
            ;;
        * )
            args+=("$1")
            ;;
    esac
    shift
done

"$dir/../zig" cc $zig_target_arg "${args[@]}"